use std::path::Path;

/// Generates `configuration.nix` content for the given commit tree.
///
/// Imports:
/// 1. `/etc/nixos/hardware-configuration.nix` — absolute, if `has_hw_config`
/// 2. `<tree_dir>/roles/<role>/main.nix` — absolute path into extracted tree
/// 3. `<tree_dir>/roles/<role>/hosts/<hostname>/main.nix` — absolute, if `hostname` is Some
///
/// Written to `/etc/nixos/configuration.nix` (standard NixOS location).
/// Profile imports (`<nixops3/profiles/...>`) resolve via `-I nixops3=<tree_dir>`
/// passed to `nixos-rebuild`.
pub fn generate_configuration_nix(
    tree_dir: &Path,
    role: &str,
    hostname: Option<&str>,
    has_hw_config: bool,
) -> String {
    let mut imports: Vec<String> = Vec::new();
    if has_hw_config {
        imports.push("/etc/nixos/hardware-configuration.nix".to_string());
    }
    imports.push(format!("{}/roles/{}/main.nix", tree_dir.display(), role));

    if let Some(h) = hostname {
        imports.push(format!("{}/roles/{}/hosts/{}/main.nix", tree_dir.display(), role, h));
    }

    let import_lines: Vec<String> = imports.iter().map(|p| format!("    {p}")).collect();

    format!(
        "# Generated by nixops3 — do not edit manually\n\
         # S3 is the source of truth. Manual edits are lost on the next poll.\n\
         {{ lib, ... }}:\n\
         {{\n  imports = [\n{}\n  ];\n\n  \
         # Bootloader guard for fresh machines. Roles managing a real bootloader\n  \
         # must override this with lib.mkForce.\n  \
         boot.loader.grub.device = lib.mkDefault \"nodev\";\n}}\n",
        import_lines.join("\n")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    const SHA: &str = "abc1234";
    const ROLE: &str = "home/production/webserver";
    const HOST: &str = "web-01.example.internal";

    fn tree_dir() -> PathBuf {
        PathBuf::from(format!("/var/lib/nixops3/commits/{SHA}"))
    }

    #[test]
    fn test_5_1_basic_no_host() {
        let out = generate_configuration_nix(&tree_dir(), ROLE, None, true);
        assert!(out.contains("/etc/nixos/hardware-configuration.nix"));
        assert!(out.contains(&format!(
            "/var/lib/nixops3/commits/{SHA}/roles/{ROLE}/main.nix"
        )));
        assert!(!out.contains(HOST), "no host import expected");
        assert!(out.contains("boot.loader.grub.device"));
    }

    #[test]
    fn test_5_2_host_included() {
        let out = generate_configuration_nix(&tree_dir(), ROLE, Some(HOST), true);
        let role_idx = out
            .find(&format!("/roles/{ROLE}/main.nix"))
            .expect("role import present");
        let host_idx = out
            .find(&format!("/roles/{ROLE}/hosts/{HOST}/main.nix"))
            .expect("host import present");
        assert!(host_idx > role_idx, "host must come after role");
    }

    #[test]
    fn test_5_3_hw_config_omitted() {
        let out = generate_configuration_nix(&tree_dir(), ROLE, None, false);
        assert!(!out.contains("hardware-configuration.nix"));
        assert!(out.contains(&format!("/roles/{ROLE}/main.nix")));
        assert!(out.contains("boot.loader.grub.device"));
    }

    #[test]
    fn test_5_4_hw_config_first() {
        let out = generate_configuration_nix(&tree_dir(), ROLE, Some(HOST), true);
        let hw = out.find("hardware-configuration.nix").unwrap();
        let role = out.find(&format!("/roles/{ROLE}/main.nix")).unwrap();
        assert!(hw < role);
    }
}
