/// Generates `configuration.nix` content.
///
/// The generated file imports only:
/// 1. `/etc/nixos/hardware-configuration.nix` — absolute, always first
/// 2. `./roles/<role>/main.nix` — role entry point
/// 3. `./roles/<role>/<hostname>/main.nix` — host overrides (only if `hostname` is Some)
///
/// Profile selection is the role's responsibility via `<nixops3/profiles/...>` imports
/// in its own `main.nix`. The daemon sets `-I nixops3=<work_dir>` so that path resolves.
pub fn generate_configuration_nix(role: &str, hostname: Option<&str>, has_hw_config: bool) -> String {
    let mut imports = Vec::new();
    if has_hw_config {
        imports.push("/etc/nixos/hardware-configuration.nix".to_string());
    }
    imports.push(format!("./roles/{}/main.nix", role));

    if let Some(h) = hostname {
        imports.push(format!("./roles/{}/{}/main.nix", role, h));
    }

    let import_lines: Vec<String> = imports.iter().map(|p| format!("    {}", p)).collect();

    format!(
        "# Generated by nixops3d — do not edit manually\n{{ ... }}:\n{{\n  imports = [\n{}\n  ];\n}}\n",
        import_lines.join("\n")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_5_1_basic_no_host() {
        let out = generate_configuration_nix("home/production/ada", None, true);
        assert!(out.contains("/etc/nixos/hardware-configuration.nix"));
        assert!(out.contains("./roles/home/production/ada/main.nix"));
        assert!(!out.contains("ada-01"), "no host import expected");
    }

    #[test]
    fn test_5_1b_no_hw_config() {
        let out = generate_configuration_nix("home/production/ada", None, false);
        assert!(!out.contains("hardware-configuration.nix"));
        assert!(out.contains("./roles/home/production/ada/main.nix"));
    }

    #[test]
    fn test_5_2_host_included_when_present() {
        let out = generate_configuration_nix(
            "home/production/ada",
            Some("ada-01.waldman.internal"),
            false,
        );
        assert!(out.contains("./roles/home/production/ada/main.nix"));
        assert!(out.contains("./roles/home/production/ada/ada-01.waldman.internal/main.nix"));
        let role_idx = out.find("ada/main.nix").unwrap();
        let host_idx = out.find("ada-01.waldman.internal/main.nix").unwrap();
        assert!(host_idx > role_idx, "host must come after role");
    }

    #[test]
    fn test_5_3_hardware_always_first() {
        let out = generate_configuration_nix("home/production/ada", None, true);
        let hw_idx = out.find("/etc/nixos/hardware-configuration.nix").unwrap();
        let role_idx = out.find("./roles/").unwrap();
        assert!(hw_idx < role_idx);
    }
}
